name: CI/CD Pipeline for dbt with Snowflake

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  dbt_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dbt Core and Snowflake Adapter
      run: |
        pip install dbt-snowflake

    - name: Decode and Store Snowflake Private Key
      run: |
        echo "$SNOWFLAKE_PRIVATE_KEY" | base64 --decode > ~/.ssh/snowflake_key.p8
        chmod 600 ~/.ssh/snowflake_key.p8
      env:
        SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}

    - name: Set up dbt profile
      run: |
        mkdir -p ~/.dbt
        cat > ~/.dbt/profiles.yml <<EOL
        my_dbt_project:
          target: dev
          outputs:
            dev:
              type: snowflake
              account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
              user: ${{ secrets.SNOWFLAKE_USER }}
              role: ${{ secrets.SNOWFLAKE_ROLE }}
              database: ${{ secrets.SNOWFLAKE_DATABASE }}
              schema: ${{ secrets.SNOWFLAKE_SCHEMA }}
              warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
              private_key_path: ~/.ssh/snowflake_key.p8
        EOL

    - name: Run dbt Commands
      run: |
        dbt debug
        dbt run
        dbt test
