name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    name: Thoushif Pre-Commit Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Pre-Commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit install

      - name: Run Pre-Commit
        run: pre-commit run --all-files

  dbt-snowflake:
    name: Install dbt & Run Tests
    runs-on: ubuntu-latest
    needs: pre-commit

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dbt & Snowflake Adapter
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-snowflake

      - name: Verify dbt Installation
        run: dbt --version

      - name: Run dbt Debug
        run: dbt debug

      - name: Run dbt Tests
        run: dbt test
