repos:
  # SQLFluff Hooks
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: "3.3.1"  # Use the latest stable version
    hooks:
      - id: sqlfluff-lint
        args:
          - "--dialect"
          - "snowflake"
      - id: sqlfluff-fix
        args:
          - "--dialect"
          - "snowflake"

  # Pre-commit Hook
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"  # Use the latest stable version
    hooks:
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-toml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-added-large-files
      - id: name-tests-test
      - id: check-symlinks
      - id: check-merge-conflict
        args: ["--assume-in-merge"]
      - id: debug-statements
      - id: detect-private-key
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-ast
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: no-commit-to-branch
        args:
          - "--branch=master"
          - "--branch=develop"
        exclude: "foo.txt"

  # Gitleaks Hook for Detecting Secrets
  - repo: https://github.com/gitleaks/gitleaks
    rev: "v8.23.1"
    hooks:
      - id: gitleaks
        args:
          - "--config=.gitleaks.toml"
        exclude: "(test_data/.*|logs/.*)"

  # Ruff Hooks
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.5.0"
    hooks:
      - id: ruff
        args: ["--fix"]
        types_or: ["python", "pyi", "jupyter"]
      - id: ruff-format
        types_or: ["python", "pyi", "jupyter"]

  # Additional SQLFluff Hooks with dbt Dependencies
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: "3.0.7"
    hooks:
      - id: sqlfluff-lint
        additional_dependencies:
          - "dbt-snowflake"
          - "sqlfluff-templater-dbt"
        args:
          - "--rules"
          - "L001,L002,L003,L004,L005,L006,L008,L009,L014,L027,L029,L030,L039,L041,L046,L050"
          - "--dialect"
          - "snowflake"
          - "--templater"
          - "dbt"
      - id: sqlfluff-fix
        additional_dependencies:
          - "dbt-snowflake"
          - "sqlfluff-templater-dbt"
        args:
          - "--rules"
          - "L001,L002,L003,L004,L005,L006,L008,L009,L014,L030,L039,L041,L050"
          - "--dialect"
          - "snowflake"
          - "--templater"
          - "dbt"
          - "--FIX-EVEN-UNPARSABLE"

  # dbt-Checkpoint Hooks
  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: "v2.0.1"
    hooks:
      - id: dbt-parse
      - id: dbt-docs-generate
      - id: dbt-compile
      - id: check-script-semicolon
        files: "^dbt/"
      - id: check-model-has-properties-file
        files: "^dbt/models/"
      - id: check-model-has-tests
        files: "^dbt/models/"
