repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: "3.3.1"  # Use the latest stable version
    hooks:
      - id: sqlfluff-lint
        args: ["--dialect", "snowflake"]

      - id: sqlfluff-fix
        args: ["--dialect", "snowflake"]