name: Deploy to Snowflake

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        default: "test"
        type: choice
        options:
          - Feature
          - test
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'test' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dbt
        run: pip install dbt-snowflake

      - name: Load Environment Variables
        run: |
          echo "SNOWFLAKE_ACCOUNT=${{ vars.SNOWFLAKE_ACCOUNT }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_USER=${{ vars.SNOWFLAKE_USER }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_ROLE=${{ vars.SNOWFLAKE_ROLE }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_DATABASE=${{ vars.SNOWFLAKE_DATABASE }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_WAREHOUSE=${{ vars.SNOWFLAKE_WAREHOUSE }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_SCHEMA=${{ vars.SNOWFLAKE_SCHEMA }}" >> $GITHUB_ENV

      - name: Store Private Key as a File
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" | awk '{gsub(/\\n/,"\n")}1' > ~/.dbt/snowflake_key.pem
          chmod 600 ~/.dbt/snowflake_key.pem
          echo "SNOWFLAKE_PRIVATE_KEY_PATH=$HOME/.dbt/snowflake_key.pem" >> $GITHUB_ENV

      - name: Debug - Check Private Key File
        run: |
          echo "Checking if private key file exists..."
          ls -l ~/.dbt/snowflake_key.pem || echo "Private key file not found!"
          head -5 ~/.dbt/snowflake_key.pem || echo "Unable to read key!"

      - name: Debug - Check Environment Variables
        run: |
          echo "Selected Environment: ${{ github.event.inputs.environment }}"
          echo "SNOWFLAKE_ACCOUNT: $SNOWFLAKE_ACCOUNT"
          echo "SNOWFLAKE_USER: $SNOWFLAKE_USER"
          echo "SNOWFLAKE_ROLE: $SNOWFLAKE_ROLE"
          echo "SNOWFLAKE_DATABASE: $SNOWFLAKE_DATABASE"
          echo "SNOWFLAKE_WAREHOUSE: $SNOWFLAKE_WAREHOUSE"
          echo "SNOWFLAKE_SCHEMA: $SNOWFLAKE_SCHEMA"

      - name: Test dbt Connection
        run: dbt debug

      - name: Run dbt Models
        run: dbt run
