name: Deploy to Snowflake

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}  # ✅ Dynamically select environment

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dbt
        run: pip install dbt-snowflake

      - name: Load Environment Variables
        run: |
          echo "SNOWFLAKE_ACCOUNT=${{ vars.SNOWFLAKE_ACCOUNT }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_USER=${{ vars.SNOWFLAKE_USER }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_ROLE=${{ vars.SNOWFLAKE_ROLE }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_DATABASE=${{ vars.SNOWFLAKE_DATABASE }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_WAREHOUSE=${{ vars.SNOWFLAKE_WAREHOUSE }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_SCHEMA=${{ vars.SNOWFLAKE_SCHEMA }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_PASSWORD=${{ secrets.SNOWFLAKE_PASSWORD }}" >> $GITHUB_ENV

      - name: Debug - Display Environment Variables
        run: |
          echo "Selected Environment: ${{ github.event.inputs.environment }}"
          echo "SNOWFLAKE_ACCOUNT: $SNOWFLAKE_ACCOUNT"
          echo "SNOWFLAKE_USER: $SNOWFLAKE_USER"
          echo "SNOWFLAKE_ROLE: $SNOWFLAKE_ROLE"
          echo "SNOWFLAKE_DATABASE: $SNOWFLAKE_DATABASE"
          echo "SNOWFLAKE_WAREHOUSE: $SNOWFLAKE_WAREHOUSE"
          echo "SNOWFLAKE_SCHEMA: $SNOWFLAKE_SCHEMA"

      - name: Store Secret in File
        run: |
          echo "$SNOWFLAKE_PASSWORD" > secret_debug.txt
          ls -l secret_debug.txt
          cat secret_debug.txt


      - name: Test dbt Connection
        run: dbt debug

      - name: Run dbt Models
        run: dbt run
