name: Deploy dbt Schema Changes

on:
  push:
    branches:
      - main  # Change to match your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🛠️ Checkout code
        uses: actions/checkout@v3

      - name: ⚡ Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: 📦 Install dbt
        run: |
          pip install dbt-snowflake

      - name: Store Private Key as a File
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" | awk '{gsub(/\\n/,"\n")}1' > ~/.dbt/snowflake_key.pem
          chmod 600 ~/.dbt/snowflake_key.pem
          echo "SNOWFLAKE_PRIVATE_KEY_PATH=$HOME/.dbt/snowflake_key.pem" >> $GITHUB_ENV
      - name: Debug - Check Private Key File
        run: |
          echo "Checking if private key file exists..."
          ls -l ~/.dbt/snowflake_key.pem || echo "Private key file not found!"
          head -5 ~/.dbt/snowflake_key.pem || echo "Unable to read key!"

      - name: 🏗 Run dbt Schema Changes
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: |
          dbt debug
          dbt run
          dbt test
